server:
  port: 8089

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: support-service
  messages:
    encoding: utf-8

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_versioned_data: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: consort-redis-support-service
      port: 6379

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
